// <auto-generated />
using IbmOpsHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IbmOpsHub.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("IbmOpsHub.Data.Entities.JobRecord", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("Component").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("component");
            b.Property<string>("Details").IsRequired().HasColumnType("jsonb").HasColumnName("details");
            b.Property<string>("ExternalId").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("external_id");
            b.Property<DateTime?>("FinishedAt").HasColumnType("timestamp with time zone").HasColumnName("finished_at");
            b.Property<string>("Name").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("name");
            b.Property<DateTime>("PolledAt").HasColumnType("timestamp with time zone").HasColumnName("polled_at");
            b.Property<DateTime?>("StartedAt").HasColumnType("timestamp with time zone").HasColumnName("started_at");
            b.Property<string>("Status").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("status");
            b.HasKey("Id");
            b.HasIndex("Component", "PolledAt");
            b.HasIndex("ExternalId");
            b.ToTable("job_records");
        });
#pragma warning restore 612, 618
    }
}
